snow_url:
  description: "The URL of your SNOW Instance"
  type: "string"
  required: true
snow_username:
  description: "The username for your SNOW Instance"
  type: "string"
  required: true
snow_password:
  description: "The password for your SNOW Username"
  type: "string"
  required: true
  secret: true
aws_access_key_id:
  description: "AWS access key to use."
  type: "string"
  secret: true
  required: true
aws_secret_access_key:
  description: "AWS access secret to use."
  type: "string"
  secret: true
  required: true
region:
  description: "AWS region to use."
  type: "string"
  required: true
  default: 'us-gov-west-1'